---
title: "Numpy -  multidimensional data arrays for python"
author: "phonchi"
date: "02/17/2023"
format: 
  html:
    toc: true
    code-line-numbers: true
    code-tools: true
---

<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/phonchi/nsysu-math608/blob/master/static_files/presentations/NumPy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
  <td>
    <a target="_blank" href="https://kaggle.com/kernels/welcome?src=https://github.com/phonchi/nsysu-math608/blob/master/static_files/presentations/NumPy_tutorial.ipynb"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" /></a>
  </td>
</table>
<br/>

## Introduction

**Python** objects:

- High-level objects: integers, floating-point
- Containers: lists ([costless](https://wiki.python.org/moin/TimeComplexity) append), dictionaries (fast lookup)
- Python lists are very general. They can contain any kind of object and are dynamically typed 
- However, they do not support mathematical functions such as matrix and dot multiplications. Implementing such functions for Python lists would not be very efficient because of the dynamic typing

**NumPy** provides:

- Extension package to Python for multi-dimensional arrays
- Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when the array is created
- Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used). Moreover, Numpy arrays are memory efficient


The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provides high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices) which provides good performance 

To use `numpy` you need to import the module, using for example:

In [1]:
import numpy as np

In [2]:
a = range(1000)

In [3]:
%%timeit
a1 = []
for i in range(1000):
    a1.append(a[i]**2)

426 µs ± 19.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
%%timeit 
global a2
a2 = [i**2 for i in a]

255 µs ± 14.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
b = np.arange(1000)

In [6]:
%%timeit 
b1 = b**2

1.68 µs ± 96.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 

## Documentation
- [https://scipy-lectures.org/intro/numpy/index.html](https://scipy-lectures.org/intro/numpy/index.html)
- [https://numpy.org/doc/](https://numpy.org/doc/)

In [7]:
np.array?

Docstring:
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
    If

## Creating `numpy` arrays

There are a number of ways to initialize new `numpy` arrays, for example, from

* A Python list or tuples
* Using functions that are dedicated to generating `numpy` arrays, such as `arange`, `linspace`, etc.
* Reading data from files (`npy`)

### From Python list

For example, to create new vector and matrix arrays from Python lists, we can use the `numpy.array` function.

In [8]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])
v, type(v), v.dtype, v.shape

(array([1, 2, 3, 4]), numpy.ndarray, dtype('int32'), (4,))

In [9]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4]])
M, type(M), M.dtype, M.shape

(array([[1, 2],
        [3, 4]]),
 numpy.ndarray,
 dtype('int32'),
 (2, 2))

Note that the `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides. The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

Since it is statically typing, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [10]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, etc.

We can also explicitly define the bit size of the data types, for example: `int64`, `int16`, `float128`, `complex128`.

### Using array-generating functions

For larger arrays, it is impractical to initialize the data manually using explicit python lists. Instead, we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

In [11]:
np.arange(-1, 1, 0.1) # arguments: start, stop, step

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [12]:
# using linspace, both end points ARE included
np.linspace(0, 10, 25) # arguments: start, end, number of samples

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [13]:
from numpy import random

In [14]:
# uniform random numbers in [0,1]
np.random.rand(5,5) #argument: shape

array([[0.95856122, 0.46008766, 0.18125959, 0.29118265, 0.12936857],
       [0.66136799, 0.31069994, 0.02396709, 0.19487356, 0.2781103 ],
       [0.95491478, 0.39030392, 0.98749426, 0.11391192, 0.71392245],
       [0.45548694, 0.26654714, 0.39209578, 0.09068336, 0.1440259 ],
       [0.65795932, 0.07484714, 0.33585994, 0.38683142, 0.25092455]])

In [15]:
# standard normal distributed random numbers
np.random.randn(5,5)

array([[-0.1083494 , -1.4625737 , -1.52901998, -0.19867851, -0.69311333],
       [ 0.22918277, -0.54191491, -0.11518915, -0.39199225, -0.46892591],
       [-1.74171355,  0.04522399, -1.30233269, -0.56877774, -0.96248809],
       [ 0.47210184, -0.67675756,  0.25428361,  0.42873618,  0.94328066],
       [ 1.04585954, -1.53339424,  1.22914079,  0.83127729, -0.45995271]])

#### diag

In [16]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### zeros and ones

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.random.seed(89)
np.random.rand(5)

array([0.49969432, 0.25593713, 0.25810063, 0.09692171, 0.56418511])

In [20]:
np.random.rand(5)

array([0.01599007, 0.15259523, 0.48024773, 0.09987276, 0.41696389])

## Manipulating arrays

### Indexing and slicing

- Note that the indices begin at 0, like other Python sequences (and C/C++). In contrast, in Fortran or Matlab, indices start at 1.
- In 2D, the first dimension corresponds to rows, the second to columns.

We can index elements in an array using square brackets and indices:

In [21]:
# v is a vector, and has only one dimension, taking one index
v = np.random.rand(5) #Note it starts with zero 
v, v[3]

(array([0.91365081, 0.35071951, 0.11460437, 0.71260839, 0.10188615]),
 0.7126083905021839)

In [22]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M = np.random.rand(5,5)
M, M[2,3]

(array([[0.40570044, 0.66548144, 0.13835937, 0.83043309, 0.12319969],
        [0.58779155, 0.06309849, 0.49710274, 0.92839462, 0.80603084],
        [0.19839124, 0.34528354, 0.53473647, 0.97858347, 0.5030445 ],
        [0.3474475 , 0.21278653, 0.17745402, 0.1040286 , 0.18745545],
        [0.04031375, 0.23991727, 0.5462427 , 0.20778317, 0.99270398]]),
 0.9785834687356999)

We can get rows and columns as follows

In [23]:
M[1,:] # row 1

array([0.58779155, 0.06309849, 0.49710274, 0.92839462, 0.80603084])

In [24]:
M[:,1] # column 1

array([0.66548144, 0.06309849, 0.34528354, 0.21278653, 0.23991727])

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [25]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [26]:
A[1:3]

array([2, 3])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [27]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([1, 3, 5])

In [28]:
A[:3] # first three elements

array([1, 2, 3])

In [29]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [30]:
A = array([1,2,3,4,5])

NameError: name 'array' is not defined

In [34]:
A[-1] # the last element in the array

5

In [35]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [36]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [37]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

<div class="alert alert-success">

- Chcek "Fancy indexing" at  [https://scipy-lectures.org/intro/numpy/array_object.html#fancy-indexing ](https://scipy-lectures.org/intro/numpy/array_object.html#fancy-indexing)
    
</div>

## Linear algebra on array

Vectorizing code is the key to writing efficient numerical calculations with `Python/Numpy`. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar and array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [38]:
v = np.arange(0, 5)

In [39]:
v * 2, v + 2

(array([0, 2, 4, 6, 8]), array([2, 3, 4, 5, 6]))

In [40]:
print(A * 2)
print(A + 2)

[[ 0  2  4  6  8]
 [20 22 24 26 28]
 [40 42 44 46 48]
 [60 62 64 66 68]
 [80 82 84 86 88]]
[[ 2  3  4  5  6]
 [12 13 14 15 16]
 [22 23 24 25 26]
 [32 33 34 35 36]
 [42 43 44 45 46]]


In [41]:
a = np.arange(10000)

In [42]:
%timeit a + 1  

6.25 µs ± 186 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [43]:
l = range(10000)

In [44]:
%timeit [i+1 for i in l] 

813 µs ± 65.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behavior is **element-wise** operations:

In [45]:
A * A # element-wise multiplication

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [46]:
v * v

array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [47]:
A, v

(array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44]]),
 array([0, 1, 2, 3, 4]))

In [48]:
A.shape, v.shape

((5, 5), (5,))

In [49]:
A * v    

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

<div class="alert alert-success">
    
- See Broadcasting at  [https://scipy-lectures.org/intro/numpy/operations.html#broadcasting](https://scipy-lectures.org/intro/numpy/operations.html#broadcasting) and [https://cs231n.github.io/python-numpy-tutorial/#broadcasting](https://cs231n.github.io/python-numpy-tutorial/#broadcasting)
    
</div>

### Matrix algebra

What about matrix multiplication? There are two ways. We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [50]:
np.dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [51]:
np.dot(A, v)

array([ 30, 130, 230, 330, 430])

In [52]:
np.dot(v, v)

30

In [53]:
A.T #transpose

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

Alternatively, we can cast the array objects to the type `matrix`. This changes the behavior of the standard arithmetic operators `+, -, *` to use matrix algebra. (Become matrix operation!)

In [54]:
help(np.matrix)

Help on class matrix in module numpy:

class matrix(ndarray)
 |  matrix(data, dtype=None, copy=True)
 |  
 |  matrix(data, dtype=None, copy=True)
 |  
 |  .. note:: It is no longer recommended to use this class, even for linear
 |            algebra. Instead use regular arrays. The class may be removed
 |            in the future.
 |  
 |  Returns a matrix from an array-like object, or from a string of data.
 |  A matrix is a specialized 2-D array that retains its 2-D nature
 |  through operations.  It has certain special operators, such as ``*``
 |  (matrix multiplication) and ``**`` (matrix power).
 |  
 |  Parameters
 |  ----------
 |  data : array_like or string
 |     If `data` is a string, it is interpreted as a matrix with commas
 |     or spaces separating columns, and semicolons separating rows.
 |  dtype : data-type
 |     Data-type of the output matrix.
 |  copy : bool
 |     If `data` is already an `ndarray`, then this flag determines
 |     whether the data is copied (the 

### Matrix computations
- The sub-module `numpy.linalg` implements basic linear algebra, such as solving linear systems, singular value decomposition, etc.

#### Inverse

In [55]:
np.linalg.det(A)

0.0

### Data processing and reshaping

Often it is useful to store datasets in Numpy arrays. Numpy provides a number of functions to calculate the statistics of datasets in arrays. 

In [56]:
# column 4
np.mean(A[:,3]), np.std(A[:,3])

(23.0, 14.142135623730951)

In [57]:
a = range(10000)
b = np.arange(10000)

In [58]:
%%timeit
sum(a)

199 µs ± 9.13 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [59]:
%%timeit
np.sum(b)

7.99 µs ± 202 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


When functions such as `min`, `max`, etc. are applied to a multidimensional arrays, it is sometimes useful to apply the calculation to the entire array, and sometimes only on a row or column basis. Using the `axis` argument we can specify how these functions should behave: 

In [60]:
m = np.random.rand(3,3)
m

array([[0.31751608, 0.41545447, 0.94062331],
       [0.17379774, 0.57561705, 0.31818086],
       [0.40848656, 0.62145644, 0.79010869]])

In [61]:
# global max
m.max()

0.9406233060883264

<center><img src="https://scipy-lectures.org/_images/reductions.png"></center>

<div align="center"> source: https://scipy-lectures.org/intro/numpy/operations.html </div>

In [62]:
# max in each column
m.max(axis=0)

array([0.40848656, 0.62145644, 0.94062331])

In [63]:
# max in each row
m.max(axis=1)

array([0.94062331, 0.57561705, 0.79010869])

Many other functions and methods in the `array` and `matrix` classes accept the same (optional) `axis` keyword argument.

The shape of a Numpy array can be modified without copying the underlying data, which makes it a fast operation even for large arrays.

In [64]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [65]:
n, m = A.shape

In [66]:
B = A.reshape((1,n*m))
B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

With `newaxis`, we can insert new dimensions in an array, for example converting a vector to a column or row matrix:

In [67]:
v = np.array([1,2,3])

In [68]:
np.shape(v)

(3,)

In [69]:
# make a column matrix of the vector v
v[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [70]:
# column matrix
v[:,np.newaxis].shape

(3, 1)

#### Stacking and repeating arrays

Using function `repeat`, `tile`, `vstack`, `hstack`, and `concatenate` we can create larger vectors and matrices from smaller ones:

## Copy and "deep copy"

- To achieve high performance, assignments in Python usually do not copy the underlying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference). 
- A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory.

In [71]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [72]:
# now B is referring to the same array data as A 
B = A 

In [73]:
# changing B affects A
B[0,0] = 10
print(B)
print(A)

[[10  2]
 [ 3  4]]
[[10  2]
 [ 3  4]]


In [74]:
np.may_share_memory(A, B)

True

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to do a so-called "deep copy" using the function `copy`:

In [75]:
B = np.copy(A)

In [76]:
# now, if we modify B, A is not affected
B[0,0] = -5
print(B)
print(A)

[[-5  2]
 [ 3  4]]
[[10  2]
 [ 3  4]]


### Memory layout matters!

<center><img src="https://scipy-lectures.org/_images/cpu-cacheline.png"></center>

<div align="center"> source: https://scipy-lectures.org/advanced/advanced_numpy/index.html </div>

In [77]:
x = np.zeros((20000,))

In [78]:
y = np.zeros((20000*67,))[::67]

In [79]:
%timeit x.sum()

9.98 µs ± 241 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [80]:
%timeit y.sum()

59.6 µs ± 3.38 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [81]:
x.strides, y.strides

((8,), (536,))

## Iterating over array elements

Generally, we want to avoid iterating over the elements of arrays whenever we can (at all costs). The reason is that in an interpreted language like Python (or MATLAB), iterations are really slow compared to vectorized operations. 

In [82]:
import math

In [83]:
%%timeit
# itersative sum
total = 0
for item in range(0, 10000):
    total += item

585 µs ± 24.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [84]:
%%timeit
# vectorized sum
np.sum(np.arange(10000))

15.2 µs ± 892 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [85]:
%%timeit
# iterative  operation
[math.exp(item) for item in range(100)]

17.9 µs ± 454 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [86]:
%%timeit
# vectorized operation
np.exp(np.arange(100)) 

2.86 µs ± 171 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Create Your Own Vectorizing functions

To get good performance we should try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [87]:
def Theta(x):
    """
    Scalar implemenation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

To get a vectorized version of Theta we can use the Numpy function `vectorize`. In many cases it can automatically vectorize a function:

In [88]:
Theta_vec = np.vectorize(Theta)

In [89]:
Theta_vec(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

### Type casting

Since Numpy arrays are *statically typed*, the type of an array does not change once created. But we can explicitly cast an array of some type to another using the `astype` functions (see also the similar `asarray` function). This always creates a new array of a new type:

In [90]:
M.dtype

dtype('float64')

In [91]:
M2 = M.astype(float)
M2

array([[0.40570044, 0.66548144, 0.13835937, 0.83043309, 0.12319969],
       [0.58779155, 0.06309849, 0.49710274, 0.92839462, 0.80603084],
       [0.19839124, 0.34528354, 0.53473647, 0.97858347, 0.5030445 ],
       [0.3474475 , 0.21278653, 0.17745402, 0.1040286 , 0.18745545],
       [0.04031375, 0.23991727, 0.5462427 , 0.20778317, 0.99270398]])

In [92]:
M2.dtype

dtype('float64')

In [93]:
M3 = M.astype(bool)
M3

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

<div class="alert alert-success">
    
- See casting at [https://scipy-lectures.org/intro/numpy/elaborate_arrays.html](https://scipy-lectures.org/intro/numpy/elaborate_arrays.html) 
    
</div>

## File I/O
- NumPy has its own binary format, not portable but with efficient I/O
- Useful when storing and reading back numpy array data. Use the functions `numpy.save` and `numpy.load`
- Matlab: scipy.io.loadmat, scipy.io.savemat

In [94]:
np.save("random-matrix.npy", M)

In [95]:
np.load("random-matrix.npy")

array([[0.40570044, 0.66548144, 0.13835937, 0.83043309, 0.12319969],
       [0.58779155, 0.06309849, 0.49710274, 0.92839462, 0.80603084],
       [0.19839124, 0.34528354, 0.53473647, 0.97858347, 0.5030445 ],
       [0.3474475 , 0.21278653, 0.17745402, 0.1040286 , 0.18745545],
       [0.04031375, 0.23991727, 0.5462427 , 0.20778317, 0.99270398]])

## Conclusion
To make the code faster using NumPy and
- Vectorizing for loops:
Find tricks to avoid for loops using numpy arrays.

- In place operations:
 `a *= 3` instead of `a = 3*a`
 
- Use views instead of copies whenever possible

- Memory arrangement is important. Keep strides small as possible for coalescing memory access

- Broadcasting:
Use broadcasting to do operations on arrays as small as possible before combining them.

- Use compiled code (The following session)

## References
- [https://scipy-lectures.org/intro/numpy/index.html](https://scipy-lectures.org/intro/numpy/index.html) - A good introduction to pydata stack
- [https://github.com/jrjohansson/scientific-python-lectures/blob/master/Lecture-2-Numpy.ipynb](https://github.com/jrjohansson/scientific-python-lectures/blob/master/Lecture-2-Numpy.ipynb) - A good introduction for NumPy though a bit of outdated
- [http://cs229.stanford.edu/section/cs229_python_tutorial/Spring_2020_Notebook.html](http://cs229.stanford.edu/section/cs229_python_tutorial/Spring_2020_Notebook.html) - Another good introduction to NumPy
- [https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html](https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html) - A great reference for broadcasting and distance calculation
- [https://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays](https://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays)- A great article for memory layout behind NumPy
- [https://numpy.org/doc/stable/user/numpy-for-matlab-users.html](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html) - A Numpy guide for MATLAB users
- [http://mathesaurus.sourceforge.net/r-numpy.html](http://mathesaurus.sourceforge.net/r-numpy.html) - A Numpy guide for R users